import Head from 'next/head';
import { useRouter } from 'next/router';
import { signIn, signOut, useSession } from 'next-auth/react';
import React from 'react';

export default function Login() {
	const router = useRouter();
	const { data: sessionData } = useSession();

	React.useEffect(() => {
		if (sessionData) {
			void router.push('/');
		}
	}, [sessionData, router]);

	return (
		<>
			<Head>
				<title>Gastosa</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<button
					className="btn-primary btn rounded-full"
					onClick={
						sessionData ? () => void signOut() : () => void signIn()
					}
				>
					{sessionData ? 'Sign out' : 'Sign in'}
				</button>
			</main>
		</>
	);
}
